name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: education/autograding-command-grader@v1
